version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  # node-exporter:
  #   image: prom/node-exporter
  #   ports:
  #     - "9100:9100"

  # mysql-exporter:
  #   image: prom/mysqld-exporter:latest
  #   ports:
  #     - "9104:9104"
  #   environment:
  #     - DATA_SOURCE_NAME=root:password@(mysql:3306)/
  #   depends_on:
  #     - db

volumes:
  grafana-storage: 