name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install Dependencies
        run: |
          cd backend
          composer install
      - name: Run Tests
        run: |
          cd backend
          php artisan test
      - name: Build Docker Image
        run: |
          cd backend
          docker build -t market-backend .

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      - name: Run Tests
        run: |
          cd frontend
          npm run test
      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Build Docker Image
        run: |
          cd frontend
          docker build -t market-frontend . 